[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
trading_vault = "4aeW1288H4t5oSmUhmrxmVfvuhFgYrtPSj6BGwCC4djv"

[programs.devnet]
trading_vault = "4aeW1288H4t5oSmUhmrxmVfvuhFgYrtPSj6BGwCC4djv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/wsl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
testSetup = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/setup.ts"
vaultInitialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultInitialize.ts"
vaultInitDeposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultInitDeposit.ts"

[test]
startup_wait = 30000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/dump/tokenmetadata.so"