[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
trading_vault = "FViAQrdsZ2RuEi3pWKMjecLvr232p4EbTPH9GeEEBPNm"

[programs.devnet]
trading_vault = "FViAQrdsZ2RuEi3pWKMjecLvr232p4EbTPH9GeEEBPNm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=bf788362-5f53-41d2-9230-e48586e76a06"
wallet = "/home/wsl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
testSetup = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/setup.ts"
vaultInitialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultInitialize.ts"
vaultInitDeposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultInitDeposit.ts"
vaultDeposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultDeposit.ts"
vaultWithdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultWithdraw.ts"
vaultClosePosition = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/script/vaultClosePosition.ts"

[test]
startup_wait = 30000

[test.validator]
url = "https://api.mainnet-beta.solana.com" 

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/dump/tokenmetadata.so"